### ISSUE TITLE
Nested kbd tags not rendered properly

### ISSUE THREAD

**Issue by mrmanc** [RickTalken/kbdextension#1]
Love that I’ve found this markdown extension to make it easier to add my new favourite HTML tag to our documentation.

I like to nest kbd tags where there is a combination of more than one key such as in a keyboard shortcut. This is valid HTML, but this extension doesn’t appear to support nested elements.

For example, when I use this markdown:

```markdown
[[ [[⇧]]-[[⌘]]-[[A]] ]]
```

I would expect to see this HTML:

```html
<kbd> <kbd>⇧</kbd>-<kbd>⌘</kbd>-<kbd>A</kbd> </kbd>
```

But I actually get this HTML:

```html
<kbd> [[⇧</kbd>-<kbd>⌘</kbd>-<kbd>A</kbd> ]]
```

**Comment by RickTalken** [comment]
I am pleased to hear that you have found the KBD Extension useful. The issue here is that the KBD Extension uses a simple regular expression to match opening and closing brackets.  The regular expression does not allow for nested symbols so the first matching symbol closes the group.  Recursion is required to handle nested markdown.  Unfortunately, Python's standard library `re` module does not support recursion (see [stackoverflow.com/questions/1656859/how-can-a-recursive-regexp-be-implemented-in-python](https://stackoverflow.com/questions/1656859/how-can-a-recursive-regexp-be-implemented-in-python)).  There are third party libraries that do support recursive regex patterns but I am reluctant to create a dependency on a third party library. I may reconsider it if there is demand but I would prefer to keep this package lean.  In the meantime, there are a few other ways to create nested `<kbd>` tags in your markdown.

- The KBD Extension supports [brackets](https://github.com/RickTalken/kbdextension#brackets-markdown), [braces](https://github.com/RickTalken/kbdextension#braces-markdown), and [parenthesis](https://github.com/RickTalken/kbdextension#parenthesis-markdown).  Braces and parenthesis are disabled by default but you can enable them.  You could then nest your bracket markdown inside braces markdown:
```
{{ [[⇧]]-[[⌘]]-[[A]] }}
```
- The other options is to nest your bracket markdown inside HTML `<kbd>` tags. 
```
<kbd> [[⇧]]-[[⌘]]-[[A]] </kbd>
```

In both cases you might want to customize your css to match your style.  See the [KBD Extension configuration notes](https://github.com/RickTalken/kbdextension#mkdocs-configuration) for tips on custom styles.

**Comment by mrmanc** [comment]
That’s a great workaround—I hadn’t realised that would work. Thanks @RickTalken!
